name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm ci
          npm run build
          mv index.html dist/
      - uses: actions/checkout@v3
        with:
          ref: pages
          clean: false
      - run: |
          mv dist/* ./
          git add *.xml *.html
      - run: |
          git config user.name "Salah Rashad"
          git config user.email "salah.r.ahmed@gmail.com"
          git commit -m "update"
          git push
